#!/usr/bin/env python3
"""Bring three repo-derived facts on the site back in line with the repos.

    python portfolio_facts.py            # check: writes nothing
    python portfolio_facts.py --apply    # write

Run from the rnvizion.github.io repo root.

WHAT IS WRONG, AND WHERE EACH FACT ACTUALLY LIVES
  1. rnv-color-mcp registers TEN tools, not nine. server.py has ten unconditional
     mcp.tool(...) registrations; the tenth, place_lightness, landed 2026-09-14.
     Stated as nine on three pages: the resume, the homepage, and the bio.

  2. Ask the Corpus gates on FOUR thresholds, not three. eval/thresholds.json
     added claim_accuracy at 100% on 2026-09-17, and it is enforced, not just
     declared: evaluate.py's gate() fails on it and the CI pytest asserts it.
     The resume says "any of three".

  3. Not every project runs cross-platform CI. The five desktop apps and AIII run
     Linux + Windows. rnv-color-mcp, rnv-ask-the-corpus and rnv-publishing-agent
     run ubuntu-latest only, with no Windows or macOS anywhere in .github/. The
     resume summary says "every project under cross-platform CI". Every project
     IS under CI, so the fix removes one word rather than rewriting the claim.

WHAT IT DELIBERATELY DOES NOT TOUCH
  "5,000+ tests" -- drift-tracked by the brand repo. "Nine shipped projects" --
  a decision, still true. Every anchor below was chosen so neither figure sits
  inside it.

  blog/honest-and-wrong/ says "nine tools by name". That sentence describes what
  the resume said on June 25, in a post dated 2026-08-28. It was true of the
  thing it describes, and a dated claim moves only when the decision it records
  moves. feed.xml inherits it and is regenerated by build-feed.yml anyway.

  The one new phrase is "public-claim accuracy at 100%", built from the metric's
  own name so it reads parallel to the three gates already listed. If you want
  different words, change NEW_GATE below before you run --apply.

  Five edits, each asserting exactly one match, counted across all three files
  before anything is written. A resume that says ten while the homepage says
  nine is the drift this script exists to remove, so a partial apply is worse
  than none. Nothing is staged, committed or pushed.
"""

import sys
from pathlib import Path

NEW_GATE = "public-claim accuracy at 100%"

EDITS = [
    # (file, label, old, new, marker that exists only in the patched form)
    ("resume/index.html", "color server: ten tools",
     "Nine deterministic tools spanning",
     "Ten deterministic tools spanning",
     "Ten deterministic tools spanning"),
    ("resume/index.html", "eval: four gates",
     "any of three thresholds regresses: retrieval accuracy at or above 85%, "
     "out-of-corpus refusal at or above 90%, and false-refusal rate at or below 10%.",
     "any of four thresholds regresses: retrieval accuracy at or above 85%, "
     "out-of-corpus refusal at or above 90%, false-refusal rate at or below 10%, "
     "and " + NEW_GATE + ".",
     "any of four thresholds regresses"),
    ("resume/index.html", "summary: every project under CI",
     "every project under cross-platform CI with its quality gates",
     "every project under CI with its quality gates",
     "every project under CI with its quality gates"),
    ("index.html", "homepage: ten tools",
     "Nine tools cover mixing",
     "Ten tools cover mixing",
     "Ten tools cover mixing"),
    ("bio/index.html", "bio: ten tools",
     "exposed as nine deterministic tools",
     "exposed as ten deterministic tools",
     "exposed as ten deterministic tools"),
]

G, R, Y, C, D, N = ("\033[32m", "\033[31m", "\033[33m",
                    "\033[36m", "\033[2m", "\033[0m")


def main() -> int:
    apply = "--apply" in sys.argv
    print(f"{D}portfolio_facts.py -- ten color tools, four eval gates, "
          f"CI claim scoped to what runs{N}")
    if not Path(".git").is_dir():
        print(f"{R}Run this from the rnvizion.github.io repo root.{N}")
        return 2

    files = {}
    for path, *_ in EDITS:
        p = Path(path)
        if not p.is_file():
            print(f"{R}{path} not found. Nothing written.{N}")
            return 2
        files.setdefault(path, p.read_text(encoding="utf-8"))

    out = dict(files)
    todo, done = 0, 0
    for path, label, old, new, marker in EDITS:
        s = out[path]
        n_old, n_mark = s.count(old), s.count(marker)
        if n_old == 0 and n_mark == 1:
            print(f"  {Y}skip{N}   {path}: {label} (already applied)")
            done += 1
            continue
        if n_old != 1 or n_mark != 0:
            print(f"  {R}stop{N}   {path}: {label}")
            print(f"{D}           old text matched {n_old} time(s), patched text "
                  f"{n_mark}; expected 1 and 0.{N}")
            print(f"{D}           The page moved since this script was built. "
                  f"Nothing written, in any file.{N}")
            return 1
        out[path] = s.replace(old, new, 1)
        print(f"  {G}ok{N}     {path}: {label}")
        todo += 1

    if todo == 0:
        print(f"\n{Y}All five already applied. Nothing to do.{N}")
        return 0

    if not apply:
        print(f"\n{Y}Check only. Nothing written.{N}  {todo} edit(s) ready"
              + (f", {done} already applied." if done else "."))
        print("  Re-run with --apply to write.")
        return 0

    for path in files:
        if out[path] != files[path]:
            Path(path).write_text(out[path], encoding="utf-8")
            print(f"{G}wrote{N}  {path}")

    print(f"\n{G}Nothing staged, nothing committed.{N}")
    print("  git diff --stat")
    print(f"{D}  Commit resume/index.html, index.html and bio/index.html together.{N}")
    print(f"{D}  The push runs build-og; pull before your next change.{N}")
    print(f"\n{Y}Then, in rnv-ask-the-corpus:{N} run the rebuild-corpus workflow by")
    print("  hand from its Actions tab. It only triggers on its own files, so")
    print("  until it runs, Ask the Corpus keeps answering nine tools and three gates.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
